### ISSUE TITLE
Modify folder

### ISSUE THREAD

**Issue by netboy3** [doy/rbw#117] opened 2023-04-26 22:15 UTC
Is there a way to modify an existing entry's folder using rbw?

**Comment by doy** [comment] 2023-07-18 05:21
no, this is currently not implemented. i'd be open to a pull request though!

**Comment by doy** [comment] 2023-07-18 05:27
actually, this is pretty much a duplicate of #35, so i'm going to close this in favor of that one, but i'd still be interested in patches

**Closed by doy** 2023-07-18 05:27 UTC
Labels: enhancement, good first issue
