### ISSUE TITLE
rbw fails to build due to crate `Region` failing to build

### ISSUE THREAD

**Issue by nikkicoon** [doy/rbw#105] opened 2023-02-24 12:14 UTC
I'm trying to package rbw for pkgsrc (I'm building on NetBSD/amd64, but it's a multi platform system PM).

It currently fails to build, I've reported this upstream at https://github.com/darfink/region-rs/issues/23 but it looks like after 1 year no commits that the crate has been abandoned by its developer.

Old log included in upstream link, new log:
```
   Compiling region v3.0.0
error[E0412]: cannot find type `QueryIter` in module `os`
 --> /usr/work/security/rbw/work/vendor/region-3.0.0/src/query.rs:7:24
  |
7 |   iterator: Option<os::QueryIter>,
  |                        ^^^^^^^^^ not found in `os`
  |
help: consider importing this struct
  |
1 | use crate::QueryIter;
  |
help: if you import `QueryIter`, refer to it directly
  |
7 -   iterator: Option<os::QueryIter>,
7 +   iterator: Option<QueryIter>,
  |

error[E0433]: failed to resolve: could not find `QueryIter` in `os`
  --> /usr/work/security/rbw/work/vendor/region-3.0.0/src/query.rs:15:9
   |
15 |     os::QueryIter::new(origin, size).map(|iterator| Self {
   |         ^^^^^^^^^ not found in `os`
   |
help: consider importing this struct
   |
1  | use crate::QueryIter;
   |
help: if you import `QueryIter`, refer to it directly
   |
15 -     os::QueryIter::new(origin, size).map(|iterator| Self {
15 +     QueryIter::new(origin, size).map(|iterator| Self {
   |

Some errors have detailed explanations: E0412, E0433.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `region` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
*** Error code 101

Stop.
```

**Comment by nikicoon** [comment] 2023-02-24 12:26
The actual core issue might be that region needs to have a NetBSD implementation added? I haven't worked much with rust.

**Comment by doy** [comment] 2023-07-18 05:15
yeah, it does look like the issue is a missing netbsd implementation. unfortunately, i don't have access to any netbsd machines, so i can't help here myself/:

**Comment by pfr-dev** [comment] 2024-01-31 11:23
I'm getting the exact same issue. Would love to use `rbw` on NetBSD. Might try rally some support in the BSD community.

**Comment by 0323pin** [comment] 2024-01-31 11:46
@pfr-dev this, https://github.com/darfink/region-rs/pull/14 fixes it but, it hasn't been merged.

**Comment by 0323pin** [comment] 2024-01-31 20:05
@nikkicoon and @pfr-dev, I've just pushed a package to the [wip-repository](http://mail-index.netbsd.org/pkgsrc-wip-changes/2024/01/31/msg029350.html), please do some testing.

**Comment by pfr-dev** [comment] 2024-02-01 00:19
> @nikkicoon and @pfr-dev, I've just pushed a package to the wip-repository, please do some testing.

Thanks! I can confirm this is working on NetBSD 9.3_Stable

**Comment by 0323pin** [comment] 2024-02-01 16:56
I've now merged the package into the [main branch](https://mail-index.netbsd.org/pkgsrc-changes/2024/02/01/msg292255.html).

It would be good to get that commit merged into `region`, though. Carrying this workaround for a long time may turn out painful.

**Comment by pfr-dev** [comment] 2024-03-12 00:40
> It would be good to get that commit merged into `region`, though.

Patch has been [merged](https://github.com/darfink/region-rs/pull/14) and a new [release tag v3.0.1](https://github.com/darfink/region-rs/releases/tag/v3.0.1) created.

Thanks @0323pin !

**Comment by doy** [comment] 2024-04-20 18:54
i've bumped the `region` dependency in 5c47355, and this should be included in the 1.10 release. thanks for the work here!

**Closed by doy** 2024-04-20 18:54 UTC
Labels: bug, help wanted

**Comment by 0323pin** [comment] 2024-04-20 20:17
@doy Thanks!
Is a new release planned?

**Comment by doy** [comment] 2024-04-20 22:17
just released!
